// 主入口: 全部模块。具名 re-export 保证 tsc 产物静态可分析。
export { TIMEOUT_MS, LOAD_TIMEOUT_MS, MAX_WATER, DEFAULT_MAX_TURNS, TURN_INTERVAL_MS, TURN_INTERVALS_MS, START_MONEY, MAX_LOG_LINES, MAX_LOGS_PER_TURN } from './config';
export type { Position, InternalOperation, TileInfo, CropInfo, DroneInfo, GameInfo, PlayerView, CropData, Tile, DroneState, PlayerState, WorldState, SnapshotTile, SnapshotDrone, SnapshotPlayer, SnapshotState, GameResult, GameEvent, GameMode, Frame } from './types';
export { TileType, CropType, CropState } from './types';
export { normalizeOp } from './ops';
export type { NormalizeResult } from './ops';
export { TILES, CROPS, isCropType, cropConfig, cropInfo } from './registry';
export type { TileTypeConfig, CropTypeConfig } from './registry';
export { SINGLE_WIDTH, SINGLE_HEIGHT, COMBAT_WIDTH, COMBAT_HEIGHT, mirrorPosition, createSingleWorld, createCombatWorld, isOwnHalf, inBounds, tileAt, samePos, placeCrop, isWater } from './maps';
export { toLocal, fromLocal, buildPlayerView, snapshotOf, findDroneAt } from './view';
export { playerApiFactory, DroneOperation, Move, Plant, CollectWater, Water, Harvest, Clear, Intercept, OPS } from './player-api';
export type { PlayerApi, PlayerConsole } from './player-api';
export { stepTurn } from './engine';
export type { DroneAction } from './engine';
export { GameController } from './game-controller';
export type { PlayerProgram, PlayerTurnResult, GamePlayer, GameControllerOptions } from './game-controller';
export { compilePlayerCode, setWasmUrl, setWasmModule } from './compile';
export type { CompileResult, CompileError } from './compile';
export { DOC_OPERATIONS, DOC_FUNCTIONS, DOC_TYPES, DOC_RULES, DOC_OVERVIEW, DOC_SECTIONS, cropDocEntries, sectionMarkdown } from './docs';
export type { DocEntry, DocSection, DocParagraphSection, DocSectionId } from './docs';
